### ISSUE TITLE
ChromiumPage 浏览器启动后报错websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden

### ISSUE THREAD

**Issue by w-jt** [g1879/DrissionPage#10]
~~~ python
# 导入
from DrissionPage import ChromiumPage

# 创建对象
page = ChromiumPage()
# 访问网页
page.get('https://www.baidu.com')
# 输入文本
page('#kw').input('DrissionPage')
# 点击按钮
page('#su').click()
# 等待页面跳转
page.wait.load_start()
# 获取所有结果
links = page.eles('tag:h3')
# 遍历并打印结果
for link in links:
    print(link.text)

~~~

**run EROR**

~~~
D:\wu\Desktop\project\pythonProject\env\Scripts\python.exe D:/wu/Desktop/project/pythonProject/main.py
Traceback (most recent call last):
  File "D:\wu\Desktop\project\pythonProject\main.py", line 5, in <module>
    page = ChromiumPage()
  File "D:\wu\Desktop\project\pythonProject\env\lib\site-packages\DrissionPage\chromium_page.py", line 29, in __init__
    super().__init__(addr_driver_opts, tab_id, timeout)
  File "D:\wu\Desktop\project\pythonProject\env\lib\site-packages\DrissionPage\chromium_base.py", line 33, in __init__
    self._connect_browser(address, tab_id)
  File "D:\wu\Desktop\project\pythonProject\env\lib\site-packages\DrissionPage\chromium_page.py", line 75, in _connect_browser
    self._init_page(tab_id)
  File "D:\wu\Desktop\project\pythonProject\env\lib\site-packages\DrissionPage\chromium_page.py", line 85, in _init_page
    super()._init_page(tab_id)
  File "D:\wu\Desktop\project\pythonProject\env\lib\site-packages\DrissionPage\chromium_base.py", line 68, in _init_page
    self._tab_obj.start()
  File "D:\wu\Desktop\project\pythonProject\env\lib\site-packages\DrissionPage\chromium_driver.py", line 183, in start
    self._ws = create_connection(self._websocket_url, enable_multithread=True)
  File "D:\wu\Desktop\project\pythonProject\env\lib\site-packages\websocket\_core.py", line 608, in create_connection
    websock.connect(url, **options)
  File "D:\wu\Desktop\project\pythonProject\env\lib\site-packages\websocket\_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "D:\wu\Desktop\project\pythonProject\env\lib\site-packages\websocket\_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "D:\wu\Desktop\project\pythonProject\env\lib\site-packages\websocket\_handshake.py", line 147, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden

Process finished with exit code 1
~~~

谷歌浏览器  版本 112.0.5615.140（正式版本） （64 位）
Python 3.9.10 （64 位）

浏览器打开后就报错

**Comment by g1879** [comment]
你的DrissionPage是什么版本？新版已经解决这个问题。

**Comment by w-jt** [comment]
DrissionPage       3.0.34

**Comment by w-jt** [comment]
> 你的DrissionPage是什么版本？新版已经解决这个问题。

DrissionPage       3.0.34

**Comment by g1879** [comment]
> DrissionPage 3.0.34

旧版在启动110以后版本Chrome时是会遇到这个问题，新版已经适配。最新版是3.2.30。

**Comment by jinyonglner** [comment]
pip install websocket-client--upgrade 
升级后解决了
