### ISSUE TITLE
ini 文件读取报错 之前3.0是好的 4.0就不行了

### ISSUE THREAD

**Issue by jinwyp** [g1879/DrissionPage#103]
ini 文件读取报错 之前3.0是好的 4.0就不行了 直接影响打包

```
def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """

    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    
    print(os.path.join(base_path, relative_path))
    return os.path.join(base_path, relative_path)


def checkIPListBlock(ipList=None):
    tempIni = resource_path('dp_configs.ini')
    print(f"==tempIni: {tempIni} ")

    co = ChromiumOptions(read_file=True, ini_path=tempIni)

    co.headless(False)
    co.save()
    page = ChromiumPage(addr_or_opts=co)
    
```

```
co = ChromiumOptions(ini_path=r'D:\dp_configs.ini)
co = ChromiumOptions(read_file=True, ini_path=‘./dp_configs.ini)
```

无论写什么 都报错 无法找到INI文件 打包exe后也无法运行 报错如下

```
Traceback (most recent call last):
  File "J:\ai\python3\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "J:\ai\pingpe\req_gui.py", line 88, in button1_click
    resultList = ipCheck.checkIPListBlock(ipListValid)
  File "J:\ai\pingpe\req.py", line 44, in checkIPListBlock
    co = ChromiumOptions(ini_path=r'.\dp_configs.ini')
  File "J:\ai\pingpe\venv\lib\site-packages\DrissionPage\_configs\chromium_options.py", line 33, in __init__
    options = om.chromium_options
  File "J:\ai\pingpe\venv\lib\site-packages\DrissionPage\_configs\options_manage.py", line 39, in __getattr__
    return self.get_option(item)
  File "J:\ai\pingpe\venv\lib\site-packages\DrissionPage\_configs\options_manage.py", line 59, in get_option
    items = self._conf.items(section)
  File "J:\ai\python3\lib\configparser.py", line 851, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'chromium_options'
```

**Comment by g1879** [comment]
https://g1879.gitee.io/beta4/whatsnew/4_0/
看4.0的变化。

**Comment by jinwyp** [comment]
我用的就是 addr_or_opts 上面的代码就是4.0版本的代码 一样报错
