### ISSUE TITLE
Parse json error

### ISSUE THREAD

**Issue by touero** [g1879/DrissionPage#120]
我的程序中在某些时候会报这个错误, 但是程序继续运行, 似乎没有影响, 我不知道这个错误是如何产生的, 我是否应该忽略它呢
python version: 3.10
DrissionPage version: 3.2.35
chrome version: 121.0.6167.139   64

Exception in thread Thread-5 (_recv_loop):
Traceback (most recent call last):
  File "C:\Users\12435\.pyenv\pyenv-win\versions\3.10.11\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\12435\.pyenv\pyenv-win\versions\3.10.11\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\zjz\TaxServices\venv3_10_11\lib\site-packages\DrissionPage\chromium_driver.py", line 123, in _recv_loop
    message = loads(message_json)
  File "C:\Users\12435\.pyenv\pyenv-win\versions\3.10.11\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\12435\.pyenv\pyenv-win\versions\3.10.11\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\12435\.pyenv\pyenv-win\versions\3.10.11\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by g1879** [comment]
升级DrissionPage就可以了。
