### ISSUE TITLE
I cant click on a button

### ISSUE THREAD

**Issue by auths1337** [g1879/DrissionPage#121]
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\flipd bumper\main.py", line 32, in <module>
    main(threadlink)
  File "C:\Users\PC\Desktop\flipd bumper\main.py", line 26, in main
    page.ele('#quick_reply_submit').click()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\DrissionPage\_units\clicker.py", line 30, in __call__
    return self.left(by_js, timeout, wait_stop)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\DrissionPage\_units\clicker.py", line 79, in left
    raise NoRectError
DrissionPage.errors.NoRectError: 该元素没有位置及大小。

**Comment by auths1337** [comment]
this is the element:
<input type="submit" class="button" value="Post Reply" tabindex="2" accesskey="s" id="quick_reply_submit" style="width: 100%; padding: 10px 6px; margin-top: 8px;">

**Comment by g1879** [comment]
有些页面有两套一模一样的按钮，但一套可以点击一套不能点击，先确认是否获取了对的元素。
如果元素是对的，那用ele.click(by_js=True)点击。
