### ISSUE TITLE
出现这个错误可能意味着程序有bug，请把错误信息和 重现方法告知作者

### ISSUE THREAD

**Issue by hhsacsb** [g1879/DrissionPage#131]
Traceback (most recent call last):
  File "D:\PythonApplication\python1\DrissionPage_douyin.py", line 47, in startTask
    _q_tit.get_screenshot(folder_path + f'dy1.png')
  File "C:\Program Files\Python38\lib\site-packages\DrissionPage\_elements\chromium_element.py", line 601, in get_screenshot
    return self.page._get_screenshot(path, name, as_bytes=as_bytes, as_base64=as_base64, full_page=False,
  File "C:\Program Files\Python38\lib\site-packages\DrissionPage\_pages\chromium_base.py", line 1090, in _get_screenshot
    png = self.run_cdp_loaded('Page.captureScreenshot', **args)['data']
  File "C:\Program Files\Python38\lib\site-packages\DrissionPage\_pages\chromium_base.py", line 429, in run_cdp_loaded
    return self.run_cdp(cmd, **cmd_args)
  File "C:\Program Files\Python38\lib\site-packages\DrissionPage\_pages\chromium_base.py", line 420, in run_cdp
    return r if __ERROR__ not in r else raise_error(r, ignore)
  File "C:\Program Files\Python38\lib\site-packages\DrissionPage\_functions\tools.py", line 255, in raise_error
    raise r
TimeoutError:
错误：timeout
方法：Page.captureScreenshot
参数：{'format': 'png', 'captureBeyondViewport': False, 'clip': {'x': 33.99147415161133, 'y': 257.9971504211426, 'width': 821.0084648132324, 'height': 309.5170249938965, 'scale': 1}, '_timeout': 30}
版本：4.0.4.5
运行时间：5.265625

**Comment by g1879** [comment]
超时应该是浏览器卡了。
