### ISSUE TITLE
代理模式下报错

### ISSUE THREAD

**Issue by MAX0100** [g1879/DrissionPage#137]
from DrissionPage import WebPage,ChromiumOptions
co = ChromiumOptions()
co.set_browser_path("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe")

co.set_proxy("http://proxy.pinet.com.cn:3628")
# print(co.proxy)
pg = WebPage(chromium_options=co)

pg.get("https://www.baidu.com") # host无127

报错：
Traceback (most recent call last):
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Program Files\Python311\Lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python311\Lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python311\Lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python311\Lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Program Files\Python311\Lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002BB6776A890>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='proxy.cnet.com.cn', port=3128): Max retries exceeded with url: http://127.0.0.1:9222/json/version (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BB6776A890>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))       

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\DrissionPage\_pages\chromium_page.py", line 311, in run_browser
    ws = get(f'http://{chromium_options.address}/json/version', headers={'Connection': 'close'})
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 514, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='proxy.cnet.com.cn', port=3128): Max retries exceeded with url: http://127.0.0.1:9222/json/version (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BB6776A890>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\code\python\Drissionpage.py", line 9, in <module>
    pg = WebPage(chromium_options=co)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\DrissionPage\_pages\web_page.py", line 28, in __new__
    return super().__new__(cls, opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\DrissionPage\_pages\chromium_page.py", line 37, in __new__      
    is_exist, browser_id = run_browser(opt)
                           ^^^^^^^^^^^^^^^^
  File "C:\Users\max\AppData\Roaming\Python\Python311\site-packages\DrissionPage\_pages\chromium_page.py", line 318, in run_browser 
    raise BrowserConnectError('\n浏览器连接失败，如使用全局代理，须设置不代理127.0.0.1地址。')
DrissionPage.errors.BrowserConnectError:

**Comment by g1879** [comment]
如使用全局代理，须设置不代理127.0.0.1地址。
报错信息已经写了处理方法。

**Comment by fxh615** [comment]
@g1879 怎么设置不代理127.0.0.1 地址，跪求
