### ISSUE TITLE
一启动谷歌浏览器就会自动关闭

### ISSUE THREAD

**Issue by qqpkat2** [g1879/DrissionPage#147]
用的是最新版本4.0.4.9，浏览器打开就会卡死，然后就关闭，程序就异常退出了

D:\Users\Desktop\DrissionPage\venv\Scripts\python.exe D:/Users/Desktop/DrissionPage/test2.py
Traceback (most recent call last):
  File "D:/Users/Desktop/DrissionPage/test2.py", line 11, in <module>
    page = ChromiumPage(co)
  File "D:\Users\Desktop\DrissionPage\venv\lib\site-packages\DrissionPage\_pages\chromium_page.py", line 64, in __init__
    super().__init__(self.address, tab_id)
  File "D:\Users\Desktop\DrissionPage\venv\lib\site-packages\DrissionPage\_pages\chromium_base.py", line 73, in __init__
    self._connect_browser(tab_id)
  File "D:\Users\Desktop\DrissionPage\venv\lib\site-packages\DrissionPage\_pages\chromium_base.py", line 116, in _connect_browser
    self._driver_init(tab_id)
  File "D:\Users\Desktop\DrissionPage\venv\lib\site-packages\DrissionPage\_pages\chromium_base.py", line 137, in _driver_init
    r = self.run_cdp('Page.getFrameTree')
  File "D:\Users\Desktop\DrissionPage\venv\lib\site-packages\DrissionPage\_pages\chromium_base.py", line 420, in run_cdp
    return r if __ERROR__ not in r else raise_error(r, ignore)
  File "D:\Users\Desktop\DrissionPage\venv\lib\site-packages\DrissionPage\_functions\tools.py", line 233, in raise_error
    raise r
DrissionPage.errors.PageDisconnectedError: 与页面的连接已断开。

Process finished with exit code 1

**Comment by g1879** [comment]
没遇到过这个问题，没办法判断哦。

**Comment by qqpkat2** [comment]
有什么方法查看日志么？

**Comment by qqpkat2** [comment]
没解决，之前是没问题的，可能是我安装了某些软件导致出现问题

**Comment by ingath** [comment]
哥，解决了吗，是哪里的问题

**Comment by pgshow** [comment]
同样遇到此问题

**Comment by babug123** [comment]
> 同样遇到此问题，版本4.1.1.2

如果你是win10 或 win11系统，我猜测应该是中途【睡眠】或【休眠】了，然后重新唤醒的。我今天测试多次。只要【休眠】，然后重新【唤醒】，之前持续运行的代码必然报错这个提示【DrissionPage.errors.PageDisconnectedError: 与页面的连接已断开。】
