### ISSUE TITLE
page.quit()问题

### ISSUE THREAD

**Issue by loneboygan** [g1879/DrissionPage#168]
![image](https://github.com/g1879/DrissionPage/assets/72730341/801e077e-44c3-4bcf-b81b-0c2438862976)
在__del__中退出浏览器时报错：
Exception ignored in: <function DouyinCookies.__del__ at 0x000002100C692EE0>
Traceback (most recent call last):
  File "E:\code\python\test\CookiesPool\login\douyin\cookies.py", line 88, in __del__
    self.page.quit()
  File "D:\software\miniconda\lib\site-packages\DrissionPage\_pages\web_page.py", line 388, in quit
    super(SessionPage, self).quit(timeout, force)
  File "D:\software\miniconda\lib\site-packages\DrissionPage\_pages\chromium_page.py", line 263, in quit
    self.browser.quit(timeout, force)
  File "D:\software\miniconda\lib\site-packages\DrissionPage\_base\browser.py", line 171, in quit
    self.run_cdp('Browser.close')
  File "D:\software\miniconda\lib\site-packages\DrissionPage\_base\browser.py", line 99, in run_cdp
    return r if __ERROR__ not in r else raise_error(r, ignore)
  File "D:\software\miniconda\lib\site-packages\DrissionPage\_functions\tools.py", line 295, in raise_error
    raise r
TimeoutError: 
错误：timeout
method：Browser.close
args：{}
版本：4.0.0b34
运行时间：1.734375
出现这个错误可能意味着程序有bug，请把错误信息和重现方法告知作者，谢谢。
报告网站：https://gitee.com/g1879/DrissionPage/issues

**Comment by g1879** [comment]
版本好旧哦，升级一下。
