### ISSUE TITLE
websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden

### ISSUE THREAD

**Issue by LunacyZeus** [g1879/DrissionPage#18]
我想远程控制已经打开的浏览器，使用cdp协议
然后出现这个报错
这是代码
`from DrissionPage import WebPage, ChromiumOptions

co = ChromiumOptions()
debugger_port = 55556
co.debugger_address = f"http://127.0.0.1:{debugger_port}"
page = WebPage(driver_or_options=co)
`

报错为
`Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\auto-login-tool\fp_dp.py", line 6, in <module>
    page = WebPage(driver_or_options=co)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\DrissionPage\web_page.py", line 54, in __init__
    self._connect_browser()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\DrissionPage\chromium_page.py", line 89, in _connect_browser
    self._driver_init(tab_id)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\DrissionPage\chromium_base.py", line 100, in _driver_init
    self._tab_obj.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\DrissionPage\chromium_driver.py", line 200, in start
    self._ws = create_connection(self._websocket_url, enable_multithread=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_core.py", line 608, in create_connection
    websock.connect(url, **options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_core.py", line 253, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_handshake.py", line 57, in handshake
    status, resp = _get_resp_headers(sock)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\websocket\_handshake.py", line 147, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden
`

我得chrome浏览器版本为
Chromium	112.0.5615.63 (正式版本) （64 位） 
修订版本	ab434de021fb61599dc448cbef23d3ca268dd95f-refs/branch-heads/5615@{#1143}
操作系统	Windows Server OS Version 1809 (Build 17763.1554)
JavaScript	V8 11.2.214.13
用户代理	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

**Comment by g1879** [comment]
浏览器加上启动参数`--remote-allow-origins=*`

**Comment by jinyonglner** [comment]
pip install websocket-client--upgrade 
升级后解决了

**Comment by luchatex** [comment]
# 关闭edge
Get-Process msedge | Stop-Process

# 启动远程调试
"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" https://www.baidu.com --remote-debugging-port=9222  --remote-allow-origins=* -headless

# 把远程调试端口映射出来
netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=48333 connectaddress=127.0.0.1 connectport=9222

# 访问json接口获取websocket地址并获取Cookie

# 关闭端口映射
netsh interface portproxy delete v4tov4 listenaddress=0.0.0.0 listenport=48333

这就是上面提到的，使用无头参数-headless存在的一个缺点，只能获取到打开的网站的Cookie。因此如果想要获取指定目标网站的Cookie，要么重复上面的动作，要么取消无头参数-headless。笔者建议取消-headless参数，打开的浏览器用户也能正常使用，因此建议使用的命令如下：

# 关闭edge
Get-Process msedge | Stop-Process

# 启动远程调试
"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" https://www.baidu.com --remote-debugging-port=9222  --remote-allow-origins=*

# 把远程调试端口映射出来
netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=48333 connectaddress=127.0.0.1 connectport=9222

# 访问json接口获取websocket地址并获取Cookie

# 关闭端口映射
netsh interface portproxy delete v4tov4 listenaddress=0.0.0.0 listenport=48333

源自：[利用远程调试获取Chromium内核浏览器Cookie](https://segmentfault.com/a/1190000044004846)](https://segmentfault.com/a/1190000044004846)
