### ISSUE TITLE
出现这个错误可能意味着程序有bug，请把错误信息和重现方法告知作者，谢谢。

### ISSUE THREAD

**Issue by IDEON114514** [g1879/DrissionPage#234]
Traceback (most recent call last):
  File "DrissionPage\_elements\chromium_element.py", line 1467, in run_js
  File "DrissionPage\_pages\chromium_base.py", line 424, in run_cdp
  File "DrissionPage\_functions\tools.py", line 234, in raise_error
TimeoutError:
错误：timeout
方法：Runtime.callFunctionOn
参数：{'functionDeclaration': 'function(){return window.getComputedStyle(this).getPropertyValue("visibility");}', 'objectId': '3485975928696490418.44.156', 'arguments': [], 'returnByValue': False, 'awaitPromise': True, 'userGesture': True, '_timeout': 30}
版本：4.0.4.23
出现这个错误可能意味着程序有bug，请把错误信息和重现方法告知作者，谢谢。
报告网站：https://gitee.com/g1879/DrissionPage/issues

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wepigplus_edge_dp.py", line 341, in <module>
  File "cmd.py", line 138, in cmdloop
  File "cmd.py", line 217, in onecmd
  File "wepigplus_edge_dp.py", line 337, in do_download
  File "wepigplus_edge_dp.py", line 292, in download_breeding_card
  File "DrissionPage\_units\waiter.py", line 82, in ele_hidden
  File "DrissionPage\_units\waiter.py", line 411, in hidden
  File "DrissionPage\_units\waiter.py", line 533, in _wait_state
  File "DrissionPage\_units\states.py", line 32, in is_displayed
  File "DrissionPage\_elements\chromium_element.py", line 497, in style
  File "DrissionPage\_elements\chromium_element.py", line 428, in run_js
  File "DrissionPage\_elements\chromium_element.py", line 1471, in run_js
TimeoutError: 执行js超时（等待30秒）。

**Comment by g1879** [comment]
超时应该是浏览器卡了。

**Comment by Shiloh520** [comment]
is_displayed 这个要如何使用呢？找不到案例，ele('元素地址').is_displayed 会提示没有这个方法
