### ISSUE TITLE
127.0.0.1:9222无法连接

### ISSUE THREAD

**Issue by GoodManWEN** [g1879/DrissionPage#235]
```py
page = ChromiumPage()
```
错误提示：
DrissionPage.errors.BrowserConnectError:
127.0.0.1:9222浏览器无法链接。
请确认：
1、该端口为浏览器
2、已添加'--remote-debugging-port=9222'启动项
3、用户文件夹没有和已打开的浏览器冲突
4、如为无界面系统，请添加'--headless=new'参数
5、如果是Linux系统，可能还要添加'--no-sandbox'启动参数
可使用ChromiumOptions设置端口和用户文件夹路径。

**代码已运行三个月，在未修改代码情况下报错**

**Comment by g1879** [comment]
这样说我也猜不出问题，这5种可能排查一下吧。

**Comment by GoodManWEN** [comment]
9222端口不是我指定的，还以为是框架自带的。

后面解决就是自然而然就好了，不清楚原因，不过错误期间可以稳定复现无法启动。

我推测是chrome版本升级导致chrome右上角提示出现错误选项，例如有安全选项未确认之类的导致

**Comment by blueair5** [comment]
我就第一次可以正常运行，后面就提示这个。

**Comment by vlinglandy** [comment]
我也遇到这个问题，解决了吗

**Comment by skinnyshy** [comment]
使用set_local_port 设置个其他端口就可以了，另外这个问题的报错日志如下：
```shell
Traceback (most recent call last):
  File "/opt/drissionpage_scripts/test_drissionpge.py", line 9, in <module>
    page = ChromiumPage()
  File "/usr/local/lib/python3.10/dist-packages/DrissionPage/_pages/chromium_page.py", line 23, in __new__
    browser = Chromium(addr_or_opts=addr_or_opts)
  File "/usr/local/lib/python3.10/dist-packages/DrissionPage/_base/chromium.py", line 43, in __new__
    is_headless, browser_id, is_exists = run_browser(opt)
  File "/usr/local/lib/python3.10/dist-packages/DrissionPage/_base/chromium.py", line 458, in run_browser
    is_exists = connect_browser(chromium_options)
  File "/usr/local/lib/python3.10/dist-packages/DrissionPage/_functions/browser.py", line 57, in connect_browser
    raise BrowserConnectError(f'\n{address}浏览器连接失败。\n请确认：\n'
DrissionPage.errors.BrowserConnectError: 
```
```python
co = ChromiumOptions()
co = co.set_local_port('9111')
co = co.set_argument('--no-sandbox')
co = co.headless()
# 初始化page对象并且调用co配置,参考官方文档：https://www.drissionpage.cn/ChromiumPage/create_page_obj#-%E7%94%A8%E7%A8%8B%E5%BA%8F%E5%90%AF%E5%8A%A8%E7%9A%84%E6%B5%8F%E8%A7%88%E5%99%A8
page = ChromiumPage(co)
```
