### ISSUE TITLE
[Errno 24] Too many open files

### ISSUE THREAD

**Issue by yoursock** [g1879/DrissionPage#248]
使用多线程获取数据时，使用代理的情况下，代理失效需要关闭浏览器，重新设置代理再加载页面，
可能因为 self.browser.quit(timeout, force) 关闭浏览器中有强制终止进程的情况，导致一些文件或者网络句柄没有及时关闭（资源回收），导致的资源泄露。 是不是需要在这里做下资源的强制回收。

Exception ignored in: <finalize object at 0x7f098d9db3e0; dead>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.11/weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/tempfile.py", line 894, in _cleanup
    cls._rmtree(name, ignore_errors=ignore_errors)
  File "/root/anaconda3/lib/python3.11/tempfile.py", line 890, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/root/anaconda3/lib/python3.11/shutil.py", line 732, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.11/shutil.py", line 635, in _rmtree_safe_fd
    onerror(os.scandir, path, sys.exc_info())
  File "/root/anaconda3/lib/python3.11/shutil.py", line 631, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
         ^^^^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files: 'dp_tmp_path128/UserTempFolder/tmpvcq34dtc'
![D1DD0CB2-B421-4067-9E4B-A6A8ABAE19C8](https://github.com/g1879/DrissionPage/assets/38520161/b305a495-248b-4e31-964f-0ae583991339)

**Comment by yoursock** [comment]
目前可行的解决方案是自定义tmp_path, 然后在更新tmp_path后移除之前的tmp_path中的临时文件。

**Comment by yoursock** [comment]
在通过配置tmp_path，更改tmp_path然后再删除上个tmp_path后，看起来不会出现tmp_file过多的问题。但是遇到了这个问题：
Exception in thread Thread-9326 (_handle_event_loop):
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
  File "/root/anaconda3/lib/python3.11/threading.py", line 975, in run
  File "/root/anaconda3/lib/python3.11/site-packages/DrissionPage/_base/driver.py", line 156, in _handle_event_loop
  File "/root/anaconda3/lib/python3.11/site-packages/DrissionPage/_base/browser.py", line 89, in _onTargetCreated
  File "/root/anaconda3/lib/python3.11/site-packages/DrissionPage/_base/driver.py", line 54, in __init__
  File "/root/anaconda3/lib/python3.11/site-packages/DrissionPage/_base/driver.py", line 202, in start
  File "/root/anaconda3/lib/python3.11/site-packages/websocket/_core.py", line 592, in create_connection
  File "/root/anaconda3/lib/python3.11/site-packages/websocket/_core.py", line 248, in connect
  File "/root/anaconda3/lib/python3.11/site-packages/websocket/_http.py", line 120, in connect
  File "/root/anaconda3/lib/python3.11/site-packages/websocket/_http.py", line 164, in _open_socket
  File "/root/anaconda3/lib/python3.11/socket.py", line 232, in __init__
OSError: [Errno 24] Too many open files
![046E70F9-5E88-446e-A6C8-77471ABCB553](https://github.com/g1879/DrissionPage/assets/38520161/e80bb2e0-748f-45e8-8789-93076d53fb64)

**Comment by yoursock** [comment]
通过ulimit -n 查看当前会话的文件句柄数限制，ulimit -n 4096 临时调整成4096，也可以调整成其他大小的数字，小于系统限制就可以。
