### ISSUE TITLE
使用监听的时候大概率会触发元素没有找到元素的异常，而实际元素是存在并且被正确点击了的

### ISSUE THREAD

**Issue by xzhingithub** [g1879/DrissionPage#269]
**场景**：通过监听指定请求的方式判断登录完成或获取指定请求的数据
**代码逻辑**：开启监听，然后打开指定登录页面，填写账号密码点击登录，然后使用循环的方式获取数据包，等待获取到匹配的数据包后再退出循环
**问题**：以下代码多次重复运行的时候大概率会出现：账号密码登录按钮全部都正常操作了，并且网页登录成功了，但是报下列错误：
Traceback (most recent call last):
  File "C:\Users\z\Desktop\测试\dp-demo\main.py", line 30, in <module>
    init()
  File "C:\Users\z\Desktop\测试\dp-demo\main.py", line 12, in init
    page.ele('#basic_password').input('密码', True)
  File "D:\Program Files\Python310\lib\site-packages\DrissionPage\_elements\none_element.py", line 31, in __getattr__
    raise ElementNotFoundError(None, self.method, self.args)
DrissionPage.errors.ElementNotFoundError: 
没有找到元素。
method: ele()
args: {'locator': '#basic_password', 'index': 1}
问题的核心是，如果真的元素找不到，网页是没有办法登录完成的，没有办法填写账号密码等，但是实际情况是肉眼可见的账号密码以及登录都可以正常操作，并登录成功，但是报错了，报错的元素比较随机，不固定是密码输入框，可能是账号输入框或者登录按钮。另外当我把监听相关的代码行及后面的循环全部删除，仅留正常的填写账号密码登录的情况，不会出现以上问题。
代码中敏感信息已被替换，大家如果测试，可以使用其他网站去测试，只要逻辑是一样的，就大概率可以复现该问题。
**诉求**：
希望作者或者有其他兄弟可以指出问题发生的原因，我不确定这个问题是否是[DrissionPage]的bug，感谢！

**代码如下所示**：
`from DrissionPage import ChromiumOptions, WebPage

def init():
    opt = ChromiumOptions(ini_path=r'.\setting.ini')
    page = WebPage(chromium_options=opt)
    page.clear_cache()
    page.refresh(ignore_cache=True)
    page.listen.start(targets=True, method="POST", res_type="Fetch")
    page.get('https://console.yingdao.com/user/login')
    page.ele('#basic_username').input('账号', True)
    page.ele('#basic_password').input('密码', True)
    page.ele('xpath://button[@type="button"]').click()
    count = 0
    while True:
        print(f'循环{count}')
        pkgs = page.listen.steps(timeout=0.01)
        for pkg in pkgs:
            if 'oauth/token' in pkg.url:
                print(pkg.method, pkg.resourceType, pkg.url)
                break
        else:
            count += 1
            continue
        break
    page.quit()

if __name__ == '__main__':
    init()
`

**Comment by xzhingithub** [comment]
经过大量测试，问题已经解决，在创建页面后，把加载模式设置为none()即可，该问题非BUG：
`page = WebPage(chromium_options=opt)`
`page.set.load_mode.none()`
