### ISSUE TITLE
爬虫项目 重复请求开始时报错

### ISSUE THREAD

**Issue by JHC000abc** [g1879/DrissionPage#277]
Traceback (most recent call last):
  File "D:\Project\Python\pythondevelopmenttools\venv\lib\site-packages\psutil\_pswindows.py", line 727, in wrapper
    return fun(self, *args, **kwargs)
  File "D:\Project\Python\pythondevelopmenttools\venv\lib\site-packages\psutil\_pswindows.py", line 989, in create_time
    _user, _system, created = cext.proc_times(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from GetExitCodeProcess != STILL_ACTIVE)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\Python\pythondevelopmenttools\venv\lib\site-packages\psutil\__init__.py", line 355, in _init
    self.create_time()
  File "D:\Project\Python\pythondevelopmenttools\venv\lib\site-packages\psutil\__init__.py", line 757, in create_time
    self._create_time = self._proc.create_time()
  File "D:\Project\Python\pythondevelopmenttools\venv\lib\site-packages\psutil\_pswindows.py", line 729, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: process no longer exists (pid=25940)

During handling of the above exception, another exception occurred:

**Comment by g1879** [comment]
这个不是dp报错啊。

**Comment by JHC000abc** [comment]
重启大法解决
