### ISSUE TITLE
--guest访客模式启动下无法多开标签

### ISSUE THREAD

**Issue by zili999** [g1879/DrissionPage#314]
from DrissionPage import ChromiumPage, ChromiumOptions
    url='https://www.baidu.com'
    options = (  ChromiumOptions().set_argument('--guest'))
    page = ChromiumPage(options)
    for i in range(0, 5):
        tab = page.new_tab()  # 新建标签页，获取标签页对象
        tab.get(url)

Traceback (most recent call last):
  File "E:/总/ietidlbook/demo_zs.py", line 62, in <module>
    main()
  File "E:/总/ietidlbook/demo_zs.py", line 28, in main
    tab = page.new_tab()  # 新建标签页，获取标签页对象
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\DrissionPage\_pages\chromium_page.py", line 222, in new_tab
    tab = ChromiumTab(self, tab_id=self.browser.new_tab(new_window, background, new_context))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\DrissionPage\_base\browser.py", line 213, in new_tab
    tid = self.run_cdp('Target.createTarget', **kwargs)['targetId']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\DrissionPage\_base\browser.py", line 121, in run_cdp
    return r if __ERROR__ not in r else raise_error(r, ignore)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\DrissionPage\_functions\tools.py", line 241, in raise_error
    raise r
DrissionPage.errors.CDPError: 
错误：Failed to open a new tab
方法：Target.createTarget
参数：{'url': '', '_timeout': 30}
版本：4.0.5.6

**Comment by g1879** [comment]
4.1.0.0b21已解决这个问题。
