### ISSUE TITLE
page.quit()有问题

### ISSUE THREAD

**Issue by anerg2046** [g1879/DrissionPage#339]
`
Exception ignored in: <function Login.__del__ at 0x0000014BCC18EB60>
Traceback (most recent call last):
  File "d:\work\python\spider\login.py", line 20, in __del__
  File "C:\Users\anerg\anaconda3\envs\DrissionPage\Lib\site-packages\DrissionPage\_pages\web_page.py", line 427, in quit
  File "C:\Users\anerg\anaconda3\envs\DrissionPage\Lib\site-packages\DrissionPage\_pages\chromium_page.py", line 270, in quit
  File "C:\Users\anerg\anaconda3\envs\DrissionPage\Lib\site-packages\DrissionPage\_base\browser.py", line 234, in quit
  File "C:\Users\anerg\anaconda3\envs\DrissionPage\Lib\site-packages\DrissionPage\_base\browser.py", line 121, in run_cdp
  File "C:\Users\anerg\anaconda3\envs\DrissionPage\Lib\site-packages\DrissionPage\_functions\tools.py", line 232, in raise_error
ImportError: sys.meta_path is None, Python is likely shutting down
`

```python
def __del__(self):
        self.page.quit()
```

dp版本是4.0.5.6

**Comment by anerg2046** [comment]
补充，使用的是WebPage
