### ISSUE TITLE
drissonpage和playwright對接異常

### ISSUE THREAD

**Issue by sark-shy** [g1879/DrissionPage#348]
當我使用樣例程序來轉接通過本地chrome瀏覽器啟動的page對象和browser對象時，提示 `獲取失敗`
這是我的程序：
```python
from DrissionPage.common import from_playwright
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch(channel='chrome')
    page = browser.new_page()

    try:
        # use from_playwright create DrissionPage obj
        drission_page = from_playwright(page)

        # test func
        drission_page.get("https://www.DrissionPage.cn")

    except Exception as e:
        import traceback

        print("smt error:")
        traceback.print_exc()
```
錯誤提示：
```python
smt error:
Traceback (most recent call last):
  File "C:\Users\Willy\Desktop\no_account\test.py", line 77, in <module>
    drission_page = from_playwright(page)
  File "C:\Users\xxx\xxx\xxx\xxx\\site-packages\DrissionPage\common.py", line 51, in from_playwright
    raise RuntimeError('獲取失敗。')
RuntimeError: 獲取失敗。
```
我的本地chrome版本信息為：
```text
Google Chrome | 127.0.6533.120 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | c51f2916e4a14157c276fd33c8bfb24155aac1ad-refs/branch-heads/6533@{#2000}
OS | Windows 10 Version 1607 (Build 14393.2189)
JavaScript | V8 12.7.224.18
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
```
兩個庫版本為：`drissonpage==4.0.5.6` `playwright==1.46.0`

**Comment by cuinima** [comment]
@sark-shy 
是因为from_playwright中使用了 from psutil import net_connections
需要管理员权限运行

**Comment by sark-shy** [comment]
使用管理員權限運行pycharm然後執行我的測試程序仍然出現一樣的錯誤

**Comment by g1879** [comment]
我也不了解，我没有用过playwright，这个方法可能是有问题的。
