### ISSUE TITLE
MixPage error: MixPage.commons

### ISSUE THREAD

**Issue by ubaii** [g1879/DrissionPage#401]
Traceback (most recent call last):
  File "/home/zxten/Downloads/DFLOODv3/dflood.py", line 2, in <module>
    from lib import setup_user, webdriver, flood
  File "/home/zxten/Downloads/DFLOODv3/lib/flood.py", line 3, in <module>
    from MixPage import MixPage
  File "/home/zxten/.local/lib/python3.11/site-packages/MixPage/__init__.py", line 6, in <module>
    from .mix_page import MixPage
  File "/home/zxten/.local/lib/python3.11/site-packages/MixPage/mix_page.py", line 6, in <module>
    from .base import BasePage
  File "/home/zxten/.local/lib/python3.11/site-packages/MixPage/base.py", line 10, in <module>
    from .commons.web import format_html # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'MixPage.commons'

**Comment by g1879** [comment]
MixPage库是旧的不建议使用。
