### ISSUE TITLE
DrissionPage._base.chromium.Chromium.new_tab() 报错

### ISSUE THREAD

**Issue by 1c3z** [g1879/DrissionPage#442]
get_chrome 是我自己封装的函数。

版本
 DrissionPage         4.1.0.2
python 3.10
chrome 130

```
get_chrome().new_tab()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/proj/venv/lib/python3.10/site-packages/DrissionPage/_base/chromium.py", line 178, in new_tab
    return self._new_tab(True, url=url, new_window=new_window, background=background, new_context=new_context)
  File "/opt/proj/venv/lib/python3.10/site-packages/DrissionPage/_base/chromium.py", line 308, in _new_tab
    return _new_tab_by_js(self, url, obj, new_window)
  File "/opt/proj/venv/lib/python3.10/site-packages/DrissionPage/_base/chromium.py", line 481, in _new_tab_by_js
    tab.run_js(f'window.open({url}, {new})')
  File "/opt/proj/venv/lib/python3.10/site-packages/DrissionPage/_pages/chromium_base.py", line 388, in run_js
    return self._run_js(script, *args, as_expr=as_expr, timeout=timeout)
  File "/opt/proj/venv/lib/python3.10/site-packages/DrissionPage/_pages/chromium_base.py", line 395, in _run_js
    return run_js(self, script, as_expr, self.timeouts.script if timeout is None else timeout, args)
  File "/opt/proj/venv/lib/python3.10/site-packages/DrissionPage/_elements/chromium_element.py", line 1221, in run_js
    raise JavaScriptError(f'\njavascript运行错误：\n{script}\n错误信息: \n{exceptionDetails}')
DrissionPage.errors.JavaScriptError:
javascript运行错误：
function(){window.open(, target="_blank")}
错误信息:
{'exceptionId': 12, 'text': 'Uncaught', 'lineNumber': 0, 'columnNumber': 24, 'scriptId': '46', 'exception': {'type': 'object', 'subtype': 'error', 'className': 'SyntaxError', 'description': "SyntaxError: Unexpected token ','", 'objectId': '5047625391267680190.1.3'}}
>>>
>>> get_chrome().latest_tab
<ChromiumTab browser_id=9c5bed46-725e-4d93-b6fb-7cbd59df6eac tab_id=611E5F4A13E3AA619591A04F01F38704>
>>> x = get_chrome().latest_tab
>>> x.get("http://www.baidu.com")
True
>>> get_chrome()
<DrissionPage._base.chromium.Chromium object at 0x7f6e9ff7d930>

```

1.这个报错很奇怪。

2.前段时间能用，不知道为什么突然报错。

**Comment by 1c3z** [comment]
升级了下DrissionPage 版本能用了。
