### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by ilyazanuda** [g1879/DrissionPage#447]
I can't trace this error. It occasionally appears simply when loading a URL via get. When calling the method, retry, interval, and timeout were specified. I tried reproducing the error with the internet disconnected, but it doesn't occur.

```错误：timeout
方法：Page.stopLoading
参数：{'_timeout': 30}
版本：4.0.5.6
出现这个错误可能意味着程序有bug，请把错误信息和重现方法告知作者，谢谢。
报告网站：https://gitee.com/g1879/DrissionPage/issues
 Traceback (most recent call last):
  File "/home/rex/rex-project/cardvilla.py", line 257, in main
    new_tab.get(url=post_link, retry=3, interval=5, timeout=40)
  File "/home/rex/rex-project/venv/lib/python3.12/site-packages/DrissionPage/_pages/chromium_base.py", line 480, in get
    self._url_available = self._d_connect(self._url, times=retry, interval=interval,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/rex-project/venv/lib/python3.12/site-packages/DrissionPage/_pages/chromium_base.py", line 1016, in _d_connect
    ok = self._wait_loaded(1 if yu <= 0 else yu)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/rex-project/venv/lib/python3.12/site-packages/DrissionPage/_pages/chromium_base.py", line 974, in _wait_loaded
    self.stop_loading()
  File "/home/rex/rex-project/venv/lib/python3.12/site-packages/DrissionPage/_pages/chromium_base.py", line 659, in stop_loading
    self.run_cdp('Page.stopLoading')
  File "/home/rex/rex-project/venv/lib/python3.12/site-packages/DrissionPage/_pages/chromium_base.py", line 429, in run_cdp
    return r if __ERROR__ not in r else raise_error(r, ignore)
                                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rex/rex-project/venv/lib/python3.12/site-packages/DrissionPage/_functions/tools.py", line 241, in raise_error
    raise r
TimeoutError: 
错误：timeout
方法：Page.stopLoading
参数：{'_timeout': 30}
版本：4.0.5.6
出现这个错误可能意味着程序有bug，请把错误信息和重现方法告知作者，谢谢。
报告网站：https://gitee.com/g1879/DrissionPage/issues```

**Comment by ilyazanuda** [comment]
A couple of times when this error occurred, my virtual machine, where the script was running, was extremely laggy during those moments.

**Comment by LeftMonster** [comment]
+1 same issue here
