### ISSUE TITLE
Run in virtual display on Linux (BrowserConnectError)

### ISSUE THREAD

**Issue by Lyfhael** [g1879/DrissionPage#75]
Hi,
I try to run the script in my Debian machine, which has no display. And I don't want to run it in Headless mode because Cloudflare detects this.

With undetected_chromedriver I would do this and use Xvfb virtual display, so I tried the same thing here :

```python
from DrissionPage import ChromiumPage
import time
from pyvirtualdisplay import Display

display = Display(visible=0, size=(800, 600))
display.start()
# 用 d 模式创建页面对象（默认模式）
page = ChromiumPage()
# 跳转到登录页面
page.get('https://google.com')
time.sleep(5)
page.get_screenshot("screenshot.png")
```

But I get this error :

```
Traceback (most recent call last):
  File "/root/email-reverse-lookup-tool/test.py", line 8, in <module>
    page = ChromiumPage()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/DrissionPage/chromium_page.py", line 35, in __init__
    super().__init__(addr_driver_opts, tab_id, timeout)
  File "/usr/local/lib/python3.11/site-packages/DrissionPage/chromium_base.py", line 50, in __init__
    self._connect_browser(tab_id)
  File "/usr/local/lib/python3.11/site-packages/DrissionPage/chromium_page.py", line 80, in _connect_browser
    connect_browser(self._driver_options)
  File "/usr/local/lib/python3.11/site-packages/DrissionPage/commons/browser.py", line 54, in connect_browser
    test_connect(ip, port)
  File "/usr/local/lib/python3.11/site-packages/DrissionPage/commons/browser.py", line 171, in test_connect
    raise BrowserConnectError(f'\n连接浏览器失败，可能原因：\n1、浏览器未启动\n2、{port}端口不是Chromium内核浏览器\n'
DrissionPage.errors.BrowserConnectError:
连接浏览器失败，可能原因：
1、浏览器未启动
2、9222端口不是Chromium内核浏览器
3、该浏览器未允许控制
4、和已打开的浏览器冲突
请尝试用ChromiumOptions指定别的端口和指定浏览器路径
```

Any idea how to fix this ? Thank you

**Comment by aladynjr** [comment]
can you let us know how did you solve this? Thank you
