### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by JOY6IX9INE** [g1879/DrissionPage#89]
Exception in thread Thread-13 (_recv_loop):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\DrissionPage\chromium_driver.py", line 123, in _recv_loop
    message = loads(message_json)
              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by g1879** [comment]
升级4.0.0b20可解决。

**Comment by YongquanYao** [comment]
> 升级4.0.0b20可解决。

请问哪个库升级到4.0.0b2

**Comment by donggoing** [comment]
@g1879 你好，我这边发现这个问题还是存在，4.0.0b20以及目前的4.0.3.4我都尝试了

**Comment by YongquanYao** [comment]
> @g1879 你好，我这边发现这个问题还是存在，4.0.0b20以及目前的4.0.3.4我都尝试了

我好像升级到4.0.0b20问题解决了
